"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowRight,Users,LockKeyhole} from "lucide-react";
import {GROUP_NAMES,OFFICIAL_GROUP_COUNT,PRACTICE_GROUP_ID} from "@/lib/course";
import {Header,Ornaments,Panel,Field,Button,Notice,BackLink} from "@/components/ui";
export default function Join(){
 const [group,setGroup]=useState("");const [name,setName]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const router=useRouter();
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/studio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"login",group,name,password})});const data=await r.json();if(!r.ok)throw new Error(data.error);router.push(data.destination);}catch(e){setError(e instanceof Error?e.message:"暂时无法连接，请重试。");}finally{setBusy(false);}}
 const teacher=group==="Nicole";const practice=Number(group)===PRACTICE_GROUP_ID;
 return <div className="page"><Ornaments/><Header/><main id="main" className="join-main"><div className="join-copy"><p className="eyebrow">INT6136P · 让每个人的观点被看见</p><h1>先有你的观察，<br/>再有小组的<br/><span className="green-text">共同思考。</span></h1><p className="subtitle">选择你的组名，填写自己的姓名。<br/>从理解议题开始，一步一步推进。</p><div className="join-path"><span>共情理解</span><ArrowRight/><span>定义问题</span><ArrowRight/><span>报告与反思</span></div><BackLink/></div><Panel title={teacher?"欢迎，Nicole。":"加入你的小组"} className="join-panel"><div className="round-symbol">{teacher?<LockKeyhole size={30}/>:<Users size={30}/>}</div><p className="muted">{teacher?"查看各组进展、资料和报告方案，提供反馈。":"第一次加入会自动登记。再次登录，请使用相同的组名和姓名。"}</p><form onSubmit={submit}><Field label="你的组名"><select required value={group} onChange={e=>{setGroup(e.target.value);setError("");}}><option value="">请选择小组</option>{GROUP_NAMES.map((n,i)=><option key={n} value={i+1}>{n}</option>)}<option value="Nicole">Nicole · 教师</option></select></Field>{teacher?<Field label="教师密码"><input autoComplete="current-password" type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="请输入教师密码"/></Field>:<Field label="你的姓名" hint="请使用课程中登记的姓名，避免重复创建身份。"><input autoComplete="name" required minLength={1} maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="请输入你的姓名"/></Field>}{practice?<Notice>测试组仅供试用，成员和作品不计入正式课程统计。</Notice>:null}{error?<Notice error>{error}</Notice>:null}<Button type="submit" disabled={busy||!group}>{busy?"正在打开工作区…":teacher?"进入教师工作区":"加入小组，开始共情"}<ArrowRight size={19}/></Button></form><p className="join-foot">{OFFICIAL_GROUP_COUNT} 个正式小组 · 独立测试组 · 中文过程记录</p></Panel></main></div>;
}
