"use client";
import Link from "next/link";
import {ArrowUpLeft,ArrowRight,ArrowLeft,LogOut,Check,LoaderCircle} from "lucide-react";
import type {MemberData} from "@/lib/types";
import {cloneElement,isValidElement,useId,type ReactNode} from "react";
export function Ornaments(){return <div className="ornaments" aria-hidden="true"><div className="green-ribbon"><i/></div><div className="cyan-bend"/><div className="orange-disc"/><div className="coral-rules"><i/><i/></div></div>;}
export function Header({active="",groupName,members=[],name,status,navigate}:{active?:string;groupName?:string;members?:MemberData[];name?:string;status?:string;navigate?:(url:string)=>void}){
 function link(url:string,e:React.MouseEvent){if(navigate){e.preventDefault();navigate(url);}}
 return <header className="site-header"><Link className="brand" href="/" onClick={e=>link("/",e)} aria-label="INT6136P 课程首页"><ArrowUpLeft size={38} strokeWidth={4}/><span>INT6136P</span></Link><nav aria-label="主要导航"><Link className={active==="home"?"active":""} href="/" onClick={e=>link("/",e)}>课程首页</Link><Link className={active==="project"?"active":""} href="/project/observation" onClick={e=>link("/project/observation",e)}>小组项目</Link><Link className={active==="reflection"?"active":""} href="/reflection" onClick={e=>link("/reflection",e)}>我的反思</Link></nav>{groupName?<div className="identity"><div><strong>{groupName}</strong><small>{name}</small></div><div className="avatars" role="group" aria-label={members.length+' 位成员已加入'}>{members.slice(0,6).map(m=><span key={m.id} title={m.name}>{Array.from(m.name)[0]}</span>)}{members.length>6?<span title={members.length+' 位成员'}>+{members.length-6}</span>:null}</div>{status?<span className={'save-status '+(status==="已保存"?"saved":"")} role="status">{status==="正在保存…"?<LoaderCircle size={14} className="spin"/>:status==="已保存"?<Check size={14}/>:null}{status}</span>:null}</div>:<Link href="/join" className="btn small">加入小组 <ArrowRight size={16}/></Link>}</header>;
}
export function Button({children,secondary=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{secondary?:boolean}){return <button {...props} className={'btn '+(secondary?'secondary':'')+' '+(props.className??'')}>{children}</button>;}
export function Field({label,hint,children,required,conditional=false}:{label:string;hint?:string;children:ReactNode;required?:boolean;conditional?:boolean}){const hintId=useId();const control=isValidElement<{required?:boolean;'aria-describedby'?:string}>(children)?children:null;const needed=required??control?.props.required??false;const input=control?cloneElement(control,{required:needed,...(hint?{'aria-describedby':hintId}:{})}):children;return <div className={'field '+(needed?'required-field':'')}><label><span className="field-label">{label}<span className={'field-requirement '+(needed?'required':'')}>{conditional?'添加后需填完整':needed?'必填':'选填'}</span></span>{input}</label>{hint?<small id={hintId}>{hint}</small>:null}</div>;}
export function Panel({title,eyebrow,children,className=""}:{title?:string;eyebrow?:string;children:ReactNode;className?:string}){return <section className={'panel '+className}>{eyebrow?<p className="eyebrow">{eyebrow}</p>:null}{title?<h2>{title}</h2>:null}{children}</section>;}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><span className="empty-mark" aria-hidden="true">↗</span><strong>{title}</strong>{children?<p>{children}</p>:null}</div>;}
export function Notice({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={'notice '+(error?'error':'')} role={error?'alert':'status'}>{children}</div>;}
export function SignOut({navigate}:{navigate?:(url:string)=>void}){async function leave(){await fetch('/api/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});window.location.href='/join';}return <button className="text-btn" onClick={()=>{if(navigate)navigate('/join');else void leave();}}><LogOut size={15}/>切换身份</button>;}
export function BackLink(){return <Link className="back-link" href="/"><ArrowLeft size={16}/>返回课程首页</Link>;}
export function DesignThinkingMap(){return <svg className="thinking-map" viewBox="0 0 760 430" role="img" aria-labelledby="thinking-map-title thinking-map-description"><title id="thinking-map-title">设计思维循环：共情、定义、构思、原型、测试、实施</title><desc id="thinking-map-description">从理解人群和情境到定义问题，构思报告，形成原型，用反馈测试并在呈现中迭代。各阶段可以反复回访。</desc><g fill="none" strokeWidth="58" strokeLinejoin="round"><path stroke="#fc6036" d="M300 104 C190 5 52 67 49 212"/><path stroke="#3c4650" d="M49 251 C66 387 224 434 307 343"/><path stroke="#1d70e7" d="M506 336 L306 128"/><path stroke="#10a67b" d="M305 338 L506 129"/><path stroke="#ffad05" d="M532 104 C634 13 709 84 712 212"/><path stroke="#ff4e55" d="M712 251 C697 391 613 407 522 343"/></g><g stroke="#fcf8e2" strokeWidth="5" strokeLinejoin="miter"><path fill="#fc6036" d="M16 205 L49 239 L81 205"/><path fill="#3c4650" d="M284 315 L334 315 L334 366 L307 343"/><path fill="#1d70e7" d="M284 153 L284 103 L335 103 L307 130"/><path fill="#10a67b" d="M479 104 L531 104 L531 157 L507 130"/><path fill="#ffad05" d="M680 205 L712 239 L745 205"/><path fill="#ff4e55" d="M495 366 L495 315 L546 315 L522 343"/></g><g fill="white" fontSize="22" fontWeight="800"><text x="87" y="137" transform="rotate(-45 87 137)">共情理解</text><text x="153" y="382" textAnchor="middle" dominantBaseline="central" transform="rotate(18 153 382)">定义问题</text><text x="378" y="268" transform="rotate(-46 378 268)">构思方案</text><text x="575" y="71" transform="rotate(24 575 71)">形成原型</text><text x="645" y="373" textAnchor="middle" dominantBaseline="central" transform="rotate(-22 645 373)">测试检验</text><text x="324" y="163" transform="rotate(46 324 163)">实施迭代</text></g><g fill="#fc6036" fontSize="32" fontWeight="600"><text x="164" y="223">设计</text><text x="559" y="223">思维</text></g><text x="380" y="427" textAnchor="middle" fill="#222220" fontSize="24" fontWeight="900" letterSpacing="5">设计思维 · 持续迭代</text></svg>;}
