"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, ArrowLeft, ArrowUpRight, Plus, Check, Trash2, Paperclip, MessageCircle, Download, RefreshCw } from "lucide-react";
import { COURSE_ID, PRACTICE_GROUP_ID, RESEARCH_SOURCES, SOURCE_LABELS, STEPS } from "@/lib/course";
import { type Draft, type ObservationData, type NoteSource, type SeminarSection } from "@/lib/types";
import { empathizeIssues, definitionIssues } from "@/lib/validation";
import { learningStepIssues, stepAccess, findingsIssues, focusIssues, optionalInterpretationIssues } from "@/lib/learning-path";
import { ProjectProvider, useProject, api } from "./project-context";
import { Header, Ornaments, Panel, Field, Button, Empty, Notice } from "./ui";

const HEADINGS: Record<string, [string, string, string]> = {
  observation: ["先理解人，再开始选题。", "从相关人群的处境、教育现象与近期研究出发，记录你的第一份阅读或观察。", "共情 · 理解相关人群与情境"],
  discussion: ["把不同的视角放在一起。", "交流资料与经验，追问这件事对学习者、教师或其他相关人群意味着什么。", "共情 · 小组交流"],
  evidence: ["依据与未知，都要看见。", "区分资料中的发现、你们的解释，以及尚未得到支持的判断。", "共情 · 明确依据与未知"],
  summary: ["带着理解，进入定义。", "先确认你们在关注谁、什么情境，以及为什么需要继续研究。", "共情 · 阶段小结"],
  findings: ["从资料里找到问题线索。", "比较共同点与分歧，把观点连回原始资料，避免只列文献标题。", "定义 · 整理问题线索"],
  focus: ["聚焦一个值得讨论的问题。", "选择一项对相关人群有意义、与课程有关、能在专题研讨中深入讨论的议题。", "定义 · 聚焦专题"],
  definition: ["把想法做成报告方案。", "明确研究问题与边界，再把论证过程安排进约 20 分钟的小组专题报告。", "构思与原型 · 设计报告结构"],
  review: ["先推敲，再提交。", "检验论证、反思局限，并设计能让同学真正参与思考的讨论问题。", "测试 · 推敲与预演"],
  submitted: ["你们的思考，已留下记录。", "这是一份可继续修改的报告方案；展示、课堂讨论与教师反馈会帮助你们再次迭代。", "实施与迭代 · 保存与反馈"]
};
const isResearch = (source: string) => RESEARCH_SOURCES.some(s => s === source);
const sourceLabel = (source: string) => SOURCE_LABELS[source as NoteSource] ?? "资料记录";
const present = (text: string) => !!text.trim();
const date = (value: string) => new Date(value).toLocaleString("zh-CN");

export function Workspace({ step }: { step: string }) { return <ProjectProvider><WorkspaceBody step={step} /></ProjectProvider>; }
function WorkspaceBody({ step }: { step: string }) {
  const p = useProject(); const current = STEPS.find(s => s.key === step)!; const index = STEPS.findIndex(s => s.key === step);
  const phases = Array.from(new Set(STEPS.map(s => s.phase))); const phaseIndex = phases.indexOf(current.phase);
  const record = { draft: p.draft, observations: p.data.group.observations, memberId: p.data.session.memberId!, empathizeCompleted: !!p.data.group.empathizeCompletedAt, submissionCount: p.data.group.submissions.length };
  const access = stepAccess(current.key, record); const issues = learningStepIssues(current.key, record); const [advancing, setAdvancing] = useState(false);
  async function next() { if (issues.length || advancing || index >= STEPS.length - 1) return; setAdvancing(true); try { await p.navigate(`/project/${STEPS[index + 1].key}`); } finally { setAdvancing(false); } }
  return <div className="page workspace-page"><Ornaments /><Header active="project" groupName={p.data.group.name} members={p.data.group.members} name={p.data.session.name} status={p.status} navigate={path => void p.navigate(path)} />
    <div className="workspace-layout"><aside className="path-sidebar"><h2>我们的设计思考路径</h2>
      {phases.map((phase, n) => { const steps = STEPS.filter(s => s.phase === phase); return <div key={phase} className="phase-section"><button className={`phase-title ${current.phase === phase ? (n === 0 ? "green" : "coral") : ""}`} onClick={() => void p.navigate(`/project/${steps[0].key}`)}><span>0{n + 1}</span>{phase}{n === 0 && p.data.group.empathizeCompletedAt ? <Check size={19} /> : <ArrowRight size={19} />}</button><ol>{steps.map(s => <li key={s.key} className={step === s.key ? "current" : ""}><button aria-label={`${s.number} ${s.title}${stepAccess(s.key, record) ? "，需要先完成前面的必填项" : ""}`} aria-current={step === s.key ? "step" : undefined} onClick={() => void p.navigate(`/project/${s.key}`)}><span className="path-dot" />{s.title}</button></li>)}</ol></div>; })}
      <div className="sidebar-bottom"><button className="text-btn" onClick={() => void p.navigate("/works")}><Paperclip size={16} /> 展示作品提交</button><small className="muted">独立保存展示文件与作品链接。</small><button className="text-btn" onClick={() => void p.navigate("/")}><ArrowLeft size={16} /> 返回课程首页</button><button className="text-btn" onClick={() => void p.navigate("/join")}>切换身份</button><p>{p.data.group.members.length} 位{p.data.group.id === PRACTICE_GROUP_ID ? "试用成员" : "成员已加入"}<br />每一种视角都有价值。</p></div></aside>
      <main id="main" className="workspace-main"><div className="stage-heading"><span className={`stage-number ${phaseIndex > 0 ? "define" : ""}`}>0{phaseIndex + 1}</span><div><p className="eyebrow">{HEADINGS[step][2]} · 第 {current.number} 步</p><h1>{HEADINGS[step][0]}</h1><p>{HEADINGS[step][1]}</p></div><ArrowUpRight className="heading-arrow" size={65} strokeWidth={2} /></div>
        {p.data.group.id === PRACTICE_GROUP_ID ? <Notice>测试组 · 这里的试用记录不计入正式课程进度。</Notice> : null}
        {p.error ? <Notice error><p>{p.error}</p><div className="button-row"><Button secondary onClick={() => void p.flush()}>重试保存</Button><button className="text-btn" onClick={() => p.setError("")}>关闭提示</button></div></Notice> : null}
        {access ? <Panel title="先完成前一步的必填内容。"><p>进入“{current.title}”之前，请先完成“{STEPS.find(s => s.key === access.step)?.title}”。</p><ul className="checklist">{access.issues.map(message => <li key={message}><span className="dot" />{message}</li>)}</ul><Button onClick={() => void p.navigate(`/project/${access.step}`)}>返回{STEPS.find(s => s.key === access.step)?.title} <ArrowRight size={18} /></Button></Panel> : <>
          <div className="required-guide"><p>标有<strong>必填</strong>的内容需要完成才能继续；<strong>选填</strong>内容可以留空。已开始填写的条目，请补完整或移除。</p>{!["summary", "review", "submitted"].includes(step) ? issues.length ? <div role="status"><strong>继续之前，还需要完成</strong><ul>{issues.map(message => <li key={message}>{message}</li>)}</ul></div> : <span className="requirements-ready"><Check size={16} /> 本步必填内容已完成</span> : null}</div>
          {step === "observation" ? <Observation /> : step === "discussion" ? <Discussion /> : step === "evidence" ? <Evidence /> : step === "summary" ? <Summary /> : step === "findings" ? <Findings /> : step === "focus" ? <Focus /> : step === "definition" ? <Definition /> : step === "review" ? <Review /> : <Submitted />}
          {!["summary", "review", "submitted"].includes(step) ? <div className="step-footer"><Button secondary onClick={() => void p.navigate(index ? `/project/${STEPS[index - 1].key}` : "/")}><ArrowLeft size={18} /> 返回</Button><span>{step === "observation" ? "请先保存至少一条你自己的阅读或观察记录。" : "小组内容会自动保存，也可以随时返回修改。"}</span><Button disabled={advancing || !!issues.length} onClick={() => void next()}>{advancing ? "正在检查…" : `继续：${STEPS[index + 1].title}`} <ArrowRight size={18} /></Button></div> : null}
        </>}
      </main>
    </div>
  </div>;
}
function SourceTag({ source }: { source: string }) { return <span className={`tag ${source.toLowerCase()}`}>{sourceLabel(source)}</span>; }
function Citation({ note, links = true }: { note: ObservationData; links?: boolean }) {
  return <div className="note-citation">{note.sourceDetail ? <p><strong>出处：</strong>{note.sourceDetail}</p> : null}{note.publicationYear !== null ? <p><strong>出版年份：</strong>{note.publicationYear}</p> : null}{note.referenceUrl ? <p>{links ? <a className="source-link" href={note.referenceUrl} target="_blank" rel="noopener noreferrer">查看原始资料 <ArrowUpRight size={13} /></a> : <span>{note.referenceUrl}</span>}</p> : null}</div>;
}
function NoteCard({ note, selected, onClick }: { note: ObservationData; selected?: boolean; onClick?: () => void }) {
  const body = <><div className="note-top"><strong><span className="mini-avatar">{note.member.name.slice(0, 1).toUpperCase()}</span>{note.member.name}</strong><SourceTag source={note.source} /></div><h3>{note.user}</h3><p>{note.body}</p><Citation note={note} links={!onClick} /><div className="note-meta"><span>{note.context}</span>{selected ? <Check size={16} /> : <span>{note.comments.length ? `${note.comments.length} 条讨论` : ""}</span>}</div></>;
  return onClick ? <button className={`note-card ${selected ? "selected" : ""}`} onClick={onClick} aria-pressed={selected}>{body}</button> : <article className="note-card">{body}</article>;
}
function SourcePicker({ value, onChange, researchOnly = false }: { value: string[]; onChange: (v: string[]) => void; researchOnly?: boolean }) {
  const { data } = useProject(); const notes = data.group.observations.filter(n => !researchOnly || isResearch(n.source));
  return <div className="source-picker">{notes.length ? notes.map(n => <label key={n.id}><input type="checkbox" checked={value.includes(n.id)} onChange={e => onChange(e.target.checked ? [...value, n.id] : value.filter(id => id !== n.id))} /><span><strong>{n.user}</strong><small>{n.member.name} · {sourceLabel(n.source)}{n.publicationYear ? ` · ${n.publicationYear} 年` : ""}</small><small>{n.body}</small></span></label>) : <p className="muted">{researchOnly ? "请先添加有出处和年份的研究文章、期刊论文、案例或其他公开资料。" : "先分享资料或经验，再关联记录。"}</p>}</div>;
}
function LinkedSources({ ids }: { ids: string[] }) { const { data } = useProject(); return <div className="source-links">{ids.map(id => { const note = data.group.observations.find(n => n.id === id); return note ? <span key={id} title={note.sourceDetail || note.body}><Paperclip size={12} />{note.user}{note.publicationYear ? `（${note.publicationYear}）` : ""}</span> : null; })}</div>; }
function Bibliography({ notes }: { notes: ObservationData[] }) { const research = notes.filter(n => isResearch(n.source)); return research.length ? <ol className="bibliography">{research.map(n => <li key={n.id}><strong>{n.user}</strong><p>{n.sourceDetail}{n.publicationYear ? ` · ${n.publicationYear} 年` : ""}</p>{n.referenceUrl ? <a href={n.referenceUrl} target="_blank" rel="noopener noreferrer">查看原始资料 <ArrowUpRight size={12} /></a> : null}</li>)}</ol> : <p className="muted">尚未选入公开研究资料。</p>; }
function referenceNotes(draft: Draft, notes: ObservationData[]) {
  const linked = new Set([...draft.selectedEvidenceIds, ...draft.patterns.flatMap(v => v.evidenceIds), ...draft.interpretations.flatMap(v => v.evidenceIds), ...draft.candidates.flatMap(v => v.evidenceIds), ...draft.seminarSections.flatMap(v => v.evidenceIds)]);
  return notes.filter(note => linked.has(note.id) && isResearch(note.source));
}

function Observation() {
  const p = useProject(); const own = p.data.group.observations.filter(n => n.memberId === p.data.session.memberId);
  const blank = { user: "", context: "", body: "", source: "Article" as NoteSource, sourceDetail: "", publicationYear: "", referenceUrl: "" };
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState(""); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  const key = `int6136p-reading:${p.data.session.memberId}`; const research = isResearch(form.source); const yearRequired = form.source === "Article" || form.source === "Journal";
  useEffect(() => { try { const saved = sessionStorage.getItem(key); if (saved) setForm({ ...blank, ...JSON.parse(saved) }); } catch { /* 浏览器备份失败不影响数据库保存。 */ } }, [key]); // eslint-disable-line react-hooks/exhaustive-deps
  function change(values: Partial<typeof form>) { const next = { ...form, ...values }; setForm(next); setSuccess(""); try { sessionStorage.setItem(key, JSON.stringify(next)); } catch { /* 浏览器备份为可选项。 */ } }
  function clear() { setForm(blank); setFile(null); setEditing(""); sessionStorage.removeItem(key); if (fileInput.current) fileInput.current.value = ""; }
  async function share(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); p.setError("");
    try { const result = await api("observation", { id: editing || undefined, values: { ...form, publicationYear: form.publicationYear.trim() ? Number(form.publicationYear) : null } });
      if (file) { const body = new FormData(); body.set("observationId", result.id); body.set("file", file); const response = await fetch("/api/attachment", { method: "POST", body }); if (!response.ok) { setEditing(result.id); await p.refresh(); throw new Error((await response.json()).error + " 文字已保存，请重试上传附件。"); } }
      clear(); setSuccess("你的记录已保存，小组成员现在可以查看和讨论。"); await p.refresh();
    } catch (error) { p.setError(error instanceof Error ? error.message : "暂时无法分享记录，请重试。"); } finally { setBusy(false); }
  }
  async function remove(id: string) { try { if (!await p.flush()) return; if (!window.confirm("移除这条记录？工作草稿中的相关依据链接也会移除，已经提交的历史版本会保留。")) return; await api("deleteObservation", { id }); await p.refresh(); if (editing === id) clear(); } catch (error) { p.setError((error as Error).message); } }
  return <div className="two-columns observation-columns"><Panel title="记录你的阅读与观察"><p className="muted compact">先想一想：这项教育现象涉及谁？他们处于什么情境？资料中的发现能帮助我们理解什么？优先阅读近期研究，同时保留真实经验与待验证的想法。</p><form onSubmit={share}>
    <Field required label="资料或主题标题"><input minLength={2} maxLength={600} value={form.user} onChange={e => change({ user: e.target.value })} placeholder="资料标题，或你关注的人群与教育现象" /></Field>
    <Field required label="与课程的关联" hint="写出相关人群、具体情境，以及与课程知识或概念的联系。"><textarea minLength={2} maxLength={600} rows={3} value={form.context} onChange={e => change({ context: e.target.value })} placeholder="这项资料关注……；它与课程中的……有关。" /></Field>
    <Field required label="你的阅读笔记或具体观察" hint="至少 10 个字。记录发现、论据与疑问，区分原文观点和自己的解释。"><textarea minLength={10} maxLength={5000} rows={5} value={form.body} onChange={e => change({ body: e.target.value })} placeholder="资料发现……；这对相关人群可能意味着……；我还想追问……" /></Field>
    <fieldset className="source-options"><legend>记录来源 <span className="field-requirement required">必选</span></legend>{(Object.keys(SOURCE_LABELS) as NoteSource[]).map(source => <label key={source} className={form.source === source ? "checked" : ""}><input type="radio" name="source" checked={form.source === source} onChange={() => change({ source })} />{sourceLabel(source)}</label>)}</fieldset>
    {!research ? <Notice>个人经验与待验证想法可以作为选题起点，但不能代替公开研究资料。后面需要用文章、期刊、案例或其他有出处的资料支持讨论。</Notice> : null}
    <Field required={research} label="出处或参考文献信息" hint={research ? "填写作者、资料标题、期刊或出版机构等，方便小组追溯与引用。" : "如果有相关背景或出处，可以补充。"}><textarea rows={2} maxLength={1500} value={form.sourceDetail} onChange={e => change({ sourceDetail: e.target.value })} placeholder="作者、文章或资料标题、期刊／机构……" /></Field>
    <Field required={yearRequired} label="出版年份" hint={yearRequired ? "优先使用近期研究；较早的重要文章可以保留，并在讨论中说明理由。" : "案例或其他资料若未注明日期，可以留空，并在出处中注明无日期；请勿编造年份。"}><input type="number" min={1000} max={new Date().getFullYear()} step={1} value={form.publicationYear} onChange={e => change({ publicationYear: e.target.value })} placeholder="例如：2025" /></Field>
    <Field label="原始资料链接"><input type="url" maxLength={2000} value={form.referenceUrl} onChange={e => change({ referenceUrl: e.target.value })} placeholder="https://…" /></Field>
    <label className="file-button"><Paperclip size={17} /><span>{file ? file.name : "添加资料文件或图片"}</span><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={e => { const selected = e.target.files?.[0]; if (selected && selected.size > 2000000) { p.setError("请使用小于 2 MB 的附件。"); e.target.value = ""; setFile(null); } else setFile(selected ?? null); }} /></label><small className="muted file-hint">选填 · 图片或 PDF 文件 · 最大 2 MB</small>
    {success ? <Notice>{success}</Notice> : null}<div className="button-row"><Button disabled={busy} type="submit">{busy ? "正在保存…" : editing ? "保存修改" : "分享给小组"}<ArrowRight size={18} /></Button>{editing ? <Button type="button" secondary onClick={clear}>取消修改</Button> : null}</div>
  </form></Panel><Panel title="小组的阅读与观察">{p.data.group.observations.length ? <div className="note-list">{p.data.group.observations.map(note => <div key={note.id}><NoteCard note={note} />{note.memberId === p.data.session.memberId ? <div className="note-actions"><button onClick={() => { change({ user: note.user, context: note.context, body: note.body, source: note.source, sourceDetail: note.sourceDetail, publicationYear: note.publicationYear === null ? "" : String(note.publicationYear), referenceUrl: note.referenceUrl }); setEditing(note.id); setSuccess(""); setFile(null); if (fileInput.current) fileInput.current.value = ""; }}>修改</button><button onClick={() => void remove(note.id)}>移除</button></div> : null}{note.attachment ? <a className="source-link" href={`/api/attachment?id=${note.attachment.id}`}><Paperclip size={13} />{note.attachment.filename}</a> : null}</div>)}</div> : <Empty title="第一条记录，让讨论开始。">分享你读到的研究或注意到的教育现象。小组的记录会出现在这里。</Empty>}<hr /><h3>这些资料背后，是谁的需要？</h3><p className="muted">留意研究涉及的人群、学习或教育情境，以及尚未被解释的差异。</p><div className="participation"><strong>你已分享 {own.length} 条记录</strong><span>{new Set(p.data.group.observations.map(n => n.memberId)).size} / {p.data.group.members.length} 位成员已贡献</span></div></Panel></div>;
}

function Discussion() {
  const p = useProject(); const [selected, setSelected] = useState(""); const [comment, setComment] = useState(""); const [busy, setBusy] = useState(false);
  const note = p.data.group.observations.find(n => n.id === selected) ?? p.data.group.observations[0];
  async function post(e: React.FormEvent) { e.preventDefault(); if (!note) return; setBusy(true); try { await api("comment", { observationId: note.id, body: comment }); setComment(""); await p.refresh(); } catch (error) { p.setError((error as Error).message); } finally { setBusy(false); } }
  return <><div className="discussion-top"><p className="muted">读一读彼此的记录：哪些结论相同？哪些观点存在分歧？相关人群的处境是否被充分理解？</p><span className="pill">{new Set(p.data.group.observations.map(n => n.memberId)).size} 位成员已分享</span></div><div className="two-columns discussion-columns">
    <Panel title="从彼此的视角开始"><div className="card-grid">{p.data.group.observations.map(n => <NoteCard key={n.id} note={n} selected={note?.id === n.id} onClick={() => setSelected(n.id)} />)}</div>{!note ? <Empty title="先带来自己的阅读与观察。">返回第一步，分享一条记录。</Empty> : null}<div className="member-checks">{p.data.group.members.map(m => <span key={m.id} className={p.data.group.observations.some(n => n.memberId === m.id) ? "done" : ""}>{p.data.group.observations.some(n => n.memberId === m.id) ? <Check size={13} /> : <span className="dot" />}{m.name}</span>)}</div></Panel>
    <div className="stack"><Panel title="一起追问">{note ? <><NoteCard note={note} /><p className="context-line"><strong>课程关联与情境：</strong>{note.context}</p>{note.attachment ? <a className="source-link" href={`/api/attachment?id=${note.attachment.id}`}><Paperclip size={15} />{note.attachment.filename}</a> : null}<div className="comments">{note.comments.map(c => <div key={c.id}><strong>{c.member.name}</strong><p>{c.body}</p></div>)}</div><form onSubmit={post}><Field label="补充讨论" hint="评论是选填项。你可以提出疑问、不同解释，或指出需要查证的地方。"><textarea rows={3} maxLength={2000} value={comment} onChange={e => setComment(e.target.value)} placeholder="这项发现是否也适用于……？还有什么可能的解释？" /></Field><Button secondary disabled={busy || !comment.trim()}><MessageCircle size={16} />{busy ? "正在发表…" : "发表讨论"}</Button></form></> : <p className="muted">选择一条记录，开始讨论。</p>}</Panel>
      <Panel title="我们正在关注什么？"><Field required label="小组初步关注的问题" hint="写出相关人群、情境或争议，不急着决定最终结论。"><textarea rows={4} maxLength={5000} value={p.draft.emergingFocus} onChange={e => p.patch({ emergingFocus: e.target.value })} placeholder="综合这些资料与经验，我们开始关注……，因为……" /></Field><small className="muted">这是可以修改的工作方向。定义阶段会再进一步聚焦。</small></Panel>
    </div></div></>;
}

function InterpretationsEditor() {
  const p = useProject(); const list = p.draft.interpretations;
  return <><p className="muted compact">选填：把自己的解释与原始发现分开。完全空白的新增行可以留空；已经关联资料或写了替代解释的行，需要补上观点或移除。</p>{list.map((v, i) => <div className="editor-item" key={v.id}>
    <div className="item-heading"><strong>工作解释 {i + 1}</strong><button className="icon-btn" aria-label={`移除工作解释 ${i + 1}`} onClick={() => p.patch({ interpretations: list.filter(x => x.id !== v.id) })}><Trash2 size={15} /></button></div>
    <Field conditional label="我们怎样理解这项发现？"><textarea rows={3} maxLength={5000} value={v.text} onChange={e => p.patch({ interpretations: list.map(x => x.id === v.id ? { ...x, text: e.target.value } : x) })} placeholder="这可能说明……；但目前还不能断言……" /></Field>
    <details><summary>关联支持资料（{v.evidenceIds.length} 条，选填）</summary><SourcePicker researchOnly value={v.evidenceIds} onChange={ids => p.patch({ interpretations: list.map(x => x.id === v.id ? { ...x, evidenceIds: ids } : x) })} /></details>
    <Field label="有没有其他解释？"><textarea rows={2} maxLength={5000} value={v.alternative} onChange={e => p.patch({ interpretations: list.map(x => x.id === v.id ? { ...x, alternative: e.target.value } : x) })} placeholder="另一种解释可能是……" /></Field>
  </div>)}<Button secondary className="wide" disabled={list.length >= 30} onClick={() => p.patch({ interpretations: [...list, { id: crypto.randomUUID(), text: "", evidenceIds: [], alternative: "" }] })}><Plus size={17} />添加工作解释</Button></>;
}

function UnknownsEditor() {
  const p = useProject(); const list = p.draft.unknowns;
  return <><p className="muted compact">必填：至少写出一个尚未解决的问题，并说明如何查证。可以继续查找研究、比较案例，或收集相关人群的意见。</p>{list.map((v, i) => <div className="editor-item" key={v.id}>
    <div className="item-heading"><strong>待查问题 {i + 1}</strong><button className="icon-btn" aria-label={`移除待查问题 ${i + 1}`} onClick={() => p.patch({ unknowns: list.filter(x => x.id !== v.id) })}><Trash2 size={15} /></button></div>
    <Field conditional label="我们还需要理解什么？"><textarea rows={3} maxLength={5000} value={v.question} onChange={e => p.patch({ unknowns: list.map(x => x.id === v.id ? { ...x, question: e.target.value } : x) })} placeholder="我们尚不清楚……" /></Field>
    <Field conditional label="准备怎样查证？"><textarea rows={2} maxLength={5000} value={v.method} onChange={e => p.patch({ unknowns: list.map(x => x.id === v.id ? { ...x, method: e.target.value } : x) })} placeholder="进一步查找……的研究／比较……案例／了解……的意见" /></Field>
  </div>)}<Button secondary className="wide" disabled={list.length >= 30} onClick={() => p.patch({ unknowns: [...list, { id: crypto.randomUUID(), question: "", method: "" }] })}><Plus size={17} />添加待查问题</Button></>;
}

function Evidence() {
  const p = useProject(); const selected = p.data.group.observations.filter(n => p.draft.selectedEvidenceIds.includes(n.id) && isResearch(n.source));
  return <><Panel className="context-panel"><Field required label="研究领域与关注情境"><textarea rows={3} maxLength={600} value={p.draft.researchArea} onChange={e => p.patch({ researchArea: e.target.value })} placeholder="我们关注……人群在……情境中的……现象或问题。" /></Field><Field required label="与课程知识的联系"><textarea rows={3} maxLength={600} value={p.draft.courseConnection} onChange={e => p.patch({ courseConnection: e.target.value })} placeholder="这项议题与课程中的……概念、理论或讨论有关。" /></Field></Panel>
    <div className="three-columns"><Panel title="可以引用的依据" eyebrow="01 · 资料中的发现"><p className="muted compact">必选：至少两条不同的公开资料记录，其中至少一条为研究文章或期刊论文。关注近期研究，并保留完整出处。</p><SourcePicker researchOnly value={p.draft.selectedEvidenceIds} onChange={ids => p.patch({ selectedEvidenceIds: ids })} /><p className="selection-count">已选择 {selected.length} 条资料，其中 {selected.filter(n => n.source === "Article" || n.source === "Journal").length} 条文章或期刊论文</p>{p.data.group.observations.some(n => !isResearch(n.source)) ? <Notice>个人经验和待验证想法仍保留在讨论区。它们能帮助理解情境，但不会计入公开研究资料数量。</Notice> : null}</Panel><Panel title="我们的工作解释" eyebrow="02 · 我们的理解"><InterpretationsEditor /></Panel><Panel title="仍然需要查证" eyebrow="03 · 尚未确定的部分"><UnknownsEditor /></Panel></div></>;
}

function SummaryLine({ label, text }: { label: string; text: string }) { return <div className="summary-line"><p className="eyebrow">{label}</p><p>{text.trim() || "尚未填写。"}</p></div>; }
function Summary() {
  const p = useProject(); const [busy, setBusy] = useState(false); const issues = [...empathizeIssues(p.draft, p.data.group.observations), ...optionalInterpretationIssues(p.draft)];
  async function complete() { setBusy(true); p.setError(""); try { if (!await p.flush()) return; await api("completeEmpathize", { revision: p.revision() }); await p.refresh(); await p.navigate("/project/findings"); } catch (error) { p.setError((error as Error).message); } finally { setBusy(false); } }
  return <><div className="two-columns"><Panel title="我们目前理解了什么？" className="summary-panel"><SummaryLine label="研究领域与情境" text={p.draft.researchArea} /><SummaryLine label="课程关联" text={p.draft.courseConnection} /><SummaryLine label="初步关注的问题" text={p.draft.emergingFocus} /><h3>带入下一阶段的依据</h3>{p.data.group.observations.filter(n => p.draft.selectedEvidenceIds.includes(n.id)).map(n => <NoteCard key={n.id} note={n} />)}{!p.draft.selectedEvidenceIds.length ? <p className="muted">请先在上一步选择公开资料。</p> : null}</Panel><div className="stack"><Panel title="暂时保留的疑问">{p.draft.unknowns.filter(u => present(u.question)).map(u => <div className="unknown-summary" key={u.id}><h3>{u.question}</h3><p><strong>查证方法：</strong>{u.method || "请补充查证方法。"}</p></div>)}{!p.draft.unknowns.some(u => present(u.question)) ? <p className="muted">添加至少一个待查问题与查证方法。</p> : null}</Panel><Panel title="准备好进入定义与专题研讨了吗？">{issues.length ? <ul className="checklist">{issues.map(v => <li key={v}><span className="dot" />{v}</li>)}</ul> : <Notice><Check size={17} /> 关注情境、课程关联、研究依据与待查问题已经就绪。</Notice>}<p className="muted">下一步将把这些理解聚焦成专题报告议题。你们仍可返回补充资料和修正判断。</p><Button disabled={busy || !!issues.length} onClick={() => void complete()}>{busy ? "正在保存小结…" : "确认小结，继续专题研讨"}<ArrowRight size={19} /></Button></Panel></div></div><div className="step-footer"><Button secondary onClick={() => void p.navigate("/project/evidence")}><ArrowLeft size={17} /> 返回依据与待查问题</Button><span>把理解相关人群的过程，带入问题定义。</span></div></>;
}

function Findings() {
  const p = useProject();
  return <div className="two-columns"><Panel title="回到资料与相关人群"><p className="muted">比较各项研究的对象、情境与结论：它们有哪些共同发现？哪些结论不同？这些差异怎样影响我们对问题的理解？</p>{p.data.group.observations.filter(n => p.draft.selectedEvidenceIds.includes(n.id)).map(n => <NoteCard key={n.id} note={n} />)}<hr /><h3>不要忘记这些疑问</h3>{p.draft.unknowns.filter(u => present(u.question)).map(u => <p className="unknown-summary" key={u.id}>{u.question}</p>)}</Panel><div className="stack"><Panel title="整理主题与问题线索"><p className="muted compact">必填：至少一个有内容、有关联研究依据的主题。可以记录一致观点、研究分歧或值得关注的缺口。</p>{p.draft.patterns.map((v, i) => <div className="editor-item" key={v.id}><div className="item-heading"><strong>主题线索 {i + 1}</strong><button className="icon-btn" aria-label={`移除主题线索 ${i + 1}`} onClick={() => p.patch({ patterns: p.draft.patterns.filter(x => x.id !== v.id) })}><Trash2 size={15} /></button></div><Field conditional label="这些资料共同指向什么？"><textarea rows={3} maxLength={600} value={v.title} onChange={e => p.patch({ patterns: p.draft.patterns.map(x => x.id === v.id ? { ...x, title: e.target.value } : x) })} placeholder="多项研究指出……；但在……情境中仍有分歧。" /></Field><p className="muted compact">支持资料 <span className="field-requirement required">填写后必选</span></p><SourcePicker researchOnly value={v.evidenceIds} onChange={ids => p.patch({ patterns: p.draft.patterns.map(x => x.id === v.id ? { ...x, evidenceIds: ids } : x) })} /></div>)}<Button secondary disabled={p.draft.patterns.length >= 30} onClick={() => p.patch({ patterns: [...p.draft.patterns, { id: crypto.randomUUID(), title: "", evidenceIds: [] }] })}><Plus size={16} />添加主题线索</Button></Panel><Panel title="可以继续修正的解释"><InterpretationsEditor /></Panel></div></div>;
}

function Focus() {
  const p = useProject(); const list = p.draft.candidates;
  return <div className="two-columns"><Panel title="确定一个有意义的报告主题"><p className="muted">必填：描述并选中一个候选议题，关联支持资料。可以比较多个方向，再选择对相关人群有意义、适合深入研讨的一个。</p>{list.map((v, i) => <div className={`candidate ${p.draft.selectedCandidateId === v.id ? "chosen" : ""}`} key={v.id}><div className="item-heading"><label className="candidate-radio"><input type="radio" name="focus" checked={p.draft.selectedCandidateId === v.id} onChange={() => p.patch({ selectedCandidateId: v.id })} />候选议题 {i + 1}</label><button className="icon-btn" aria-label={`移除候选议题 ${i + 1}`} onClick={() => p.patch({ candidates: list.filter(x => x.id !== v.id), ...(p.draft.selectedCandidateId === v.id ? { selectedCandidateId: "" } : {}) })}><Trash2 size={15} /></button></div><Field required={p.draft.selectedCandidateId === v.id} conditional={p.draft.selectedCandidateId !== v.id} label="这个议题想探讨什么？"><textarea rows={3} maxLength={600} value={v.title} onChange={e => p.patch({ candidates: list.map(x => x.id === v.id ? { ...x, title: e.target.value } : x) })} placeholder="针对……人群或教育情境，我们想探讨……及其影响。" /></Field><details><summary>关联研究依据（{v.evidenceIds.length} 条） <span className="field-requirement">选中议题后必选</span></summary><SourcePicker researchOnly value={v.evidenceIds} onChange={ids => p.patch({ candidates: list.map(x => x.id === v.id ? { ...x, evidenceIds: ids } : x) })} /></details></div>)}<Button secondary disabled={list.length >= 10} onClick={() => p.patch({ candidates: [...list, { id: crypto.randomUUID(), title: "", evidenceIds: [] }] })}><Plus size={17} />添加候选议题</Button></Panel><div className="stack"><Panel title="让报告帮助同学进一步思考"><SummaryLine label="关注的人群与情境" text={p.draft.researchArea} /><Field required label="报告希望带来什么学习收获？"><textarea rows={4} maxLength={5000} value={p.draft.learningGoal} onChange={e => p.patch({ learningGoal: e.target.value })} placeholder="听完报告并参与讨论后，同学能够理解、比较、判断或反思什么？" /></Field><SummaryLine label="课程关联" text={p.draft.courseConnection} /><p className="muted">主题需要有足够研究依据，也要留出分析、反思和讨论的空间。避免把主题写成一个已经确定的技术方案。</p></Panel><Panel title="还有什么没有定论？">{p.draft.unknowns.filter(u => present(u.question)).map(u => <div className="unknown-summary" key={u.id}><h3>{u.question}</h3><p>{u.method}</p></div>)}</Panel></div></div>;
}

function sectionTemplate(): SeminarSection[] {
  return [["引入：相关人群、情境与问题", 3], ["研究与案例：主要依据", 5], ["分析与论证：联系课程知识", 6], ["课堂讨论：比较观点与反思", 4], ["总结：局限与后续探索", 2]].map(([title, minutes]) => ({ id: crypto.randomUUID(), title: String(title), minutes: Number(minutes), content: "", lead: "", evidenceIds: [] }));
}
function OutlineEditor() {
  const p = useProject(); const list = p.draft.seminarSections; const total = list.reduce((sum, section) => sum + (Number.isFinite(section.minutes) ? section.minutes : 0), 0);
  function update(id: string, values: Partial<SeminarSection>) { p.patch({ seminarSections: list.map(section => section.id === id ? { ...section, ...values } : section) }); }
  return <><p className="muted">把专题报告视作一个可以预演的原型：至少完成两个环节的标题、内容与预计时间。整场报告建议约 20 分钟，系统不会要求总时长必须恰好等于 20。建议结构中的内容需要自己填写，不使用的环节可以移除。</p>
    <div className="seminar-total"><strong>当前安排：{Number(total.toFixed(1))} 分钟</strong><span>{Math.abs(total - 20) < 0.1 ? "接近 20 分钟，试讲后再调整。" : "请结合内容深度与课堂讨论，检查是否适合约 20 分钟。"}</span></div>
    {!list.length ? <Button secondary onClick={() => p.patch({ seminarSections: sectionTemplate() })}>使用五环节结构建议 <Plus size={16} /></Button> : null}
    <div className="seminar-outline">{list.map((section, i) => <div className="editor-item" key={section.id}><div className="item-heading"><strong>报告环节 {i + 1}</strong><div className="button-row"><button className="icon-btn" disabled={i === 0} aria-label={`将环节 ${i + 1} 上移`} onClick={() => { const next = [...list]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; p.patch({ seminarSections: next }); }}><ArrowUpRight size={16} /></button><button className="icon-btn" aria-label={`移除报告环节 ${i + 1}`} onClick={() => p.patch({ seminarSections: list.filter(s => s.id !== section.id) })}><Trash2 size={15} /></button></div></div>
      <Field conditional label="环节标题"><input maxLength={600} value={section.title} onChange={e => update(section.id, { title: e.target.value })} placeholder="例如：比较研究发现与真实案例" /></Field>
      <Field conditional label="预计时间（分钟）"><input type="number" min={0.1} max={60} step={0.1} value={section.minutes || ""} onChange={e => update(section.id, { minutes: e.target.value ? Number(e.target.value) : 0 })} /></Field>
      <Field conditional label="这一环节具体讲什么、怎么展开？"><textarea rows={4} maxLength={5000} value={section.content} onChange={e => update(section.id, { content: e.target.value })} placeholder="核心观点、采用的资料或案例、与课程概念的联系，以及引导同学思考的方式……" /></Field>
      <Field label="负责成员"><input maxLength={600} value={section.lead} onChange={e => update(section.id, { lead: e.target.value })} placeholder="可以在分工确定后补充" /></Field>
      <details><summary>关联本环节资料（{section.evidenceIds.length} 条，选填）</summary><SourcePicker researchOnly value={section.evidenceIds} onChange={ids => update(section.id, { evidenceIds: ids })} /></details>
    </div>)}</div><Button secondary disabled={list.length >= 30} onClick={() => p.patch({ seminarSections: [...list, { id: crypto.randomUUID(), title: "", minutes: 0, content: "", lead: "", evidenceIds: [] }] })}><Plus size={17} />添加报告环节</Button></>;
}
function Definition() {
  const p = useProject(); const chosen = p.draft.candidates.find(c => c.id === p.draft.selectedCandidateId);
  return <><div className="two-columns"><Panel title="明确研究问题与论证边界"><div className="focus-note"><span className="eyebrow">已选报告主题</span><p>{chosen?.title || "请先在上一步选择报告主题。"}</p></div>
    <Field required label="01 · 核心研究问题"><textarea rows={3} maxLength={5000} value={p.draft.researchQuestion} onChange={e => p.patch({ researchQuestion: e.target.value })} placeholder="我们要回答什么问题？这项问题与哪些相关人群或教育情境有关？" /></Field>
    <Field required label="02 · 讨论范围与边界"><textarea rows={3} maxLength={5000} value={p.draft.scope} onChange={e => p.patch({ scope: e.target.value })} placeholder="聚焦哪些人群、情境、技术或研究范围？哪些内容暂不展开？" /></Field>
    <Field required label="03 · 为什么值得探讨"><textarea rows={3} maxLength={5000} value={p.draft.rationale} onChange={e => p.patch({ rationale: e.target.value })} placeholder="这对相关人群、教育实践或课程讨论为什么重要？依据是什么？" /></Field>
    <Field required label="04 · 核心概念与课程知识"><textarea rows={3} maxLength={5000} value={p.draft.keyConcepts} onChange={e => p.patch({ keyConcepts: e.target.value })} placeholder="需要解释或采用哪些概念、理论、原则或框架？" /></Field>
  </Panel><div className="stack"><Panel title="报告要回应谁的需要？"><SummaryLine label="关注的人群与情境" text={p.draft.researchArea} /><SummaryLine label="同学的学习收获" text={p.draft.learningGoal} /><LinkedSources ids={chosen?.evidenceIds.length ? chosen.evidenceIds : p.draft.selectedEvidenceIds} /><p className="muted">依据帮助定义问题；报告结构帮助构思如何交流。不要把资料堆积当作深入分析。</p></Panel><Panel title="让原型可讨论、可修改"><ul className="checklist"><li><MessageCircle size={17} /> 为什么这样安排论证顺序？</li><li><MessageCircle size={17} /> 每项主张有哪些研究依据？</li><li><MessageCircle size={17} /> 相关人群的需要是否始终在讨论中？</li><li><MessageCircle size={17} /> 同学能在哪个环节参与比较与反思？</li></ul><p className="muted">这些是供小组交流的提示，不会自动评价报告质量。</p></Panel></div></div>
    <Panel title="构思并制作约 20 分钟的报告原型"><OutlineEditor /></Panel><Panel title="小组分工"><Field label="分工安排与协作说明" hint="选填。可以写明检索、阅读、分析、制作、试讲和讨论主持由谁负责。"><textarea rows={4} maxLength={5000} value={p.draft.divisionOfWork} onChange={e => p.patch({ divisionOfWork: e.target.value })} placeholder="我们计划这样分工……；共同检查与互相支持的方式是……" /></Field></Panel>
  </>;
}
function Review() {
  const p = useProject(); const [busy, setBusy] = useState(false);
  const issues = [...empathizeIssues(p.draft, p.data.group.observations), ...definitionIssues(p.draft), ...findingsIssues(p.draft, p.data.group.observations), ...focusIssues(p.draft, p.data.group.observations), ...optionalInterpretationIssues(p.draft)];
  const selected = referenceNotes(p.draft, p.data.group.observations);
  async function submit() { setBusy(true); p.setError(""); try { if (!await p.flush()) return; await api("submit", { revision: p.revision() }); await p.refresh(); await p.navigate("/project/submitted"); } catch (error) { p.setError((error as Error).message); } finally { setBusy(false); } }
  return <><div className="two-columns"><div className="stack">
    <Panel title="综合研究，形成自己的论证"><Field required label="综合观点与论证" hint="比较资料和案例，联系课程知识，说明你们如何回应研究问题。至少 20 个字。"><textarea rows={7} maxLength={5000} minLength={20} className="statement-input" value={p.draft.synthesis} onChange={e => p.patch({ synthesis: e.target.value })} placeholder="不同资料的共同点与分歧是……；结合课程概念，我们认为……；支持这一判断的依据是……" /></Field><LinkedSources ids={p.draft.selectedEvidenceIds} /></Panel>
    <Panel title="深入讨论，也要反思"><Field required label="批判性反思" hint="至少 20 个字。考虑研究局限、不同立场、适用情境，以及尚不能下结论的部分。"><textarea rows={5} maxLength={5000} minLength={20} value={p.draft.criticalReflection} onChange={e => p.patch({ criticalReflection: e.target.value })} placeholder="这些发现的局限是……；对不同人群可能意味着……；我们原先的理解发生了……变化。" /></Field></Panel>
    <Panel title="让同学参与思考"><Field required label="课堂讨论问题" hint="写出至少一个能引发比较、判断或反思的开放问题，至少 8 个字。"><textarea rows={4} maxLength={5000} minLength={8} value={p.draft.discussionQuestions} onChange={e => p.patch({ discussionQuestions: e.target.value })} placeholder="面对……情境，你会如何判断……？不同立场的理由可能是什么？" /></Field></Panel>
  </div><div className="stack"><Panel title="推敲与预演检查"><ul className="checklist"><li><MessageCircle size={17} /> 研究问题、相关人群与情境是否清楚？</li><li><MessageCircle size={17} /> 主要观点是否可以追溯到资料？</li><li><MessageCircle size={17} /> 是否解释了研究分歧与局限？</li><li><MessageCircle size={17} /> 讨论问题能否让同学参与深入思考？</li><li><MessageCircle size={17} /> 试讲后，内容与约 20 分钟安排是否合适？</li></ul><p className="muted">可以请一位组员扮演听众，检查哪里难以理解，再修改报告方案。</p>{issues.length ? <Notice><strong>提交前还需要完成</strong><ul>{Array.from(new Set(issues)).map(v => <li key={v}>{v}</li>)}</ul></Notice> : <Notice><Check size={17} /> 必填内容已完成，可以保存报告方案供教师查看。</Notice>}</Panel>
    <Panel title="参考资料"><Bibliography notes={selected} /></Panel><Panel title="邀请教师反馈"><Field label="希望教师反馈什么？"><textarea rows={3} maxLength={5000} value={p.draft.feedbackRequest} onChange={e => p.patch({ feedbackRequest: e.target.value })} placeholder="希望老师针对……给予建议。" /></Field><Field label="下一步准备如何探索或修改？"><textarea rows={3} maxLength={5000} value={p.draft.nextInquiry} onChange={e => p.patch({ nextInquiry: e.target.value })} placeholder="展示或试讲之前，我们还会……；收到反馈后，计划……" /></Field></Panel>
  </div></div><div className="step-footer"><Button secondary onClick={() => void p.navigate("/project/definition")}><ArrowLeft size={17} /> 返回报告原型</Button><span>提交会保存独立历史版本，不会覆盖之前的方案。</span><Button disabled={busy || !!issues.length} onClick={() => void submit()}>{busy ? "正在保存小组方案…" : "提交报告方案"}<ArrowRight size={19} /></Button></div></>;
}
function Submitted() {
  const p = useProject(); const [chosenId, setChosenId] = useState(""); const [ack, setAck] = useState(""); const item = p.data.group.submissions.find(s => s.id === chosenId) ?? p.data.group.submissions[0];
  if (!item) return <Panel title="准备保存第一份报告方案"><p>完成研究问题、报告结构、综合观点、反思与讨论问题，然后提交小组的第一个版本。</p><Button onClick={() => void p.navigate("/project/review")}>返回检查与提交 <ArrowRight size={18} /></Button></Panel>;
  const d = item.snapshot.draft; const observations = item.snapshot.observations; const selected = referenceNotes(d, observations); const total = d.seminarSections.reduce((sum, s) => sum + s.minutes, 0);
  function download() { const blob = new Blob([JSON.stringify({ course: COURSE_ID, group: p.data.group.name, ...item }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${COURSE_ID}-第${p.data.group.id}组-报告方案-版本${item.version}.json`; anchor.click(); URL.revokeObjectURL(url); setAck("小组的报告方案与研究记录已下载。"); }
  function snapshotLinks(ids: string[]) { return <div className="source-links">{ids.map(id => { const note = observations.find(n => n.id === id); return note ? <span key={id} title={note.sourceDetail}><Paperclip size={12} />{note.user}{note.publicationYear ? `（${note.publicationYear}）` : ""}</span> : null; })}</div>; }
  return <><div className="submission-banner"><div className="success-disc"><Check size={30} /></div><div><h2>报告方案已保存。</h2><p>版本 {item.version} · {item.submittedBy} 提交 · {date(item.createdAt)}</p></div><label>查看历史版本<select value={item.id} onChange={e => setChosenId(e.target.value)}>{p.data.group.submissions.map(s => <option key={s.id} value={s.id}>版本 {s.version} · {new Date(s.createdAt).toLocaleDateString("zh-CN")}</option>)}</select></label></div>
    <Notice>提交保存的是报告方案与思考过程。接下来请继续准备展示、参与课堂讨论，并根据教师与同学的反馈修改。</Notice>
    <div className="two-columns"><div className="stack">
      <Panel title="从共情理解到问题定义"><SummaryLine label="研究领域与关注情境" text={d.researchArea} /><SummaryLine label="课程关联" text={d.courseConnection} /><SummaryLine label="初步关注的问题" text={d.emergingFocus} /><SummaryLine label="选定报告主题" text={d.candidates.find(c => c.id === d.selectedCandidateId)?.title || ""} /><SummaryLine label="学习收获" text={d.learningGoal} /><SummaryLine label="核心研究问题" text={d.researchQuestion} /><SummaryLine label="范围与边界" text={d.scope} /><SummaryLine label="探讨理由" text={d.rationale} /><SummaryLine label="核心概念与课程知识" text={d.keyConcepts} /></Panel>
      <Panel title="构思与报告原型"><p className="muted">预计合计 {Number(total.toFixed(1))} 分钟</p>{d.seminarSections.filter(s => present(s.title) || present(s.content)).map((s, i) => <div className="unknown-summary" key={s.id}><h3>{i + 1}. {s.title} · {s.minutes} 分钟</h3><p>{s.content}</p>{s.lead ? <p><strong>负责成员：</strong>{s.lead}</p> : null}{snapshotLinks(s.evidenceIds)}</div>)}<SummaryLine label="小组分工" text={d.divisionOfWork} /></Panel>
      <Panel title="综合观点与论证"><p className="large-statement">{d.synthesis}</p>{snapshotLinks(d.selectedEvidenceIds)}</Panel><Panel title="批判性反思"><p>{d.criticalReflection}</p></Panel><Panel title="课堂讨论问题"><p className="large-statement green-text">{d.discussionQuestions}</p></Panel>
    </div><div className="stack"><Panel title="教师反馈">{p.data.group.feedback.length ? p.data.group.feedback.map(f => <div className="feedback" key={f.id}><span className="eyebrow">教师反馈 · {date(f.createdAt)}</span><p>{f.body}</p></div>) : <p className="muted">教师可以查看你们提交的方案。反馈会显示在这里，供小组继续修改。</p>}<SummaryLine label="我们的反馈请求" text={d.feedbackRequest} /></Panel>
      <Panel title="展示、讨论与继续迭代"><p>{d.nextInquiry || "依据仍未解决的疑问和预演结果，准备展示；收到课堂与教师反馈后，再修正论证和报告结构。"}</p><div className="future-phases"><span>准备展示</span><ArrowRight size={16} /><span>课堂讨论</span><ArrowRight size={16} /><span>反馈迭代</span></div></Panel><Panel title="参考资料"><Bibliography notes={selected} /></Panel>
      <Panel title="候选方向的比较">{d.candidates.filter(c => present(c.title)).map(c => <div className="unknown-summary" key={c.id}><strong>{c.id === d.selectedCandidateId ? "已选议题" : "曾讨论的候选议题"}</strong><p>{c.title}</p>{snapshotLinks(c.evidenceIds)}</div>)}</Panel>
      <Panel title="主题线索、解释与待查问题">{d.patterns.filter(v => present(v.title)).map(v => <div className="unknown-summary" key={v.id}><strong>主题线索</strong><p>{v.title}</p>{snapshotLinks(v.evidenceIds)}</div>)}{d.interpretations.filter(v => present(v.text)).map(v => <div className="unknown-summary" key={v.id}><strong>工作解释</strong><p>{v.text}</p>{v.alternative ? <p className="muted">其他解释：{v.alternative}</p> : null}{snapshotLinks(v.evidenceIds)}</div>)}{d.unknowns.filter(u => present(u.question)).map(u => <div className="unknown-summary" key={u.id}><h3>{u.question}</h3><p><strong>查证方法：</strong>{u.method}</p></div>)}</Panel>
      <Panel title="小组贡献记录">{item.snapshot.members.map(m => <div className="contribution-row" key={m.id}><strong>{m.name}</strong><span>{observations.filter(n => n.memberId === m.id).length} 条阅读或观察 · {observations.reduce((sum, n) => sum + n.comments.filter(c => c.member.id === m.id).length, 0)} 条讨论</span></div>)}<div className="button-row"><Button secondary onClick={download}><Download size={16} />导出记录</Button><Button secondary onClick={() => window.print()}>打印／保存为 PDF</Button></div>{ack ? <Notice>{ack}</Notice> : null}</Panel>
    </div></div><Panel title="本版本保留的个人阅读与观察"><div className="card-grid">{observations.map(n => <NoteCard key={n.id} note={n} />)}</div></Panel><Panel title="准备好展示文件或报告原型了吗？"><p>这份页面保存的是报告方案。实际展示 PPT、报告原型、讨论活动文件及作品链接，请到独立的作品区提交。</p><Button onClick={() => void p.navigate("/works")}><Paperclip size={17} />展示作品提交 <ArrowRight size={18} /></Button></Panel><div className="step-footer"><Button secondary onClick={() => void p.navigate("/project/observation")}><RefreshCw size={17} /> 补充阅读与观察</Button><Button secondary onClick={() => void p.navigate("/project/review")}>修改并提交新版本</Button><Button onClick={() => void p.navigate("/")}>返回课程首页 <ArrowRight size={18} /></Button></div>
  </>;
}
